travis:
  secure:
    BINSTAR_TOKEN: IDfvNvcbEzjEgYsZG+qiJLUHuB2BFGNSlAY6ShslZETplfYJLiL7X785LiDCDe+2sHCLWwolrCXAFnNLBRxhEF/HNFcUwyl+VspbrzR5Zso0F3btbi/acasc/68VBHiG++aqK2oQe4T8jxQ4lh7gyyZc6nMhqQYGKFWAUvt9dJTu2Sc+/MwaQ4DmURPjh2AMOPhXxTPc8VTJmXG8GdmA588Zc68s4lZ07s73P68iMALhEs+ZyEkcs5RTKOpQFCR2xQsZrlFuP2ER96JegA1M0n4WPXfg1baks9f6gYivsUrfcjhcyjVHOV+99EnwCjmoOSMAbajQ+oaVmsRGDwj1cm5X5ACH8+q3b9yroRb7GB8INT/7zPphmye/67mQyvvQ5DVFRSNYAU0Y5CBok3eo5llnWsrHSUmXY+h8UdaKtekxmbJPNtH67SI/evMfrDFJS4vARDmWPwFjHyKCXG12zLLSMHIwrjgRVzqhCGtczZbokodM4YvOPt1csDwTZO7UYaNJugtv9WPEirPO8t6QtNloYwOq0rEyIgLtB1gQTobvAqW9ZieD9trutUbd+qgcoj5jMkeb0CLycoO6Tz+0NMvmDcBHfCJ0+/SPBfYqGhtC0TJ9f5Wz0I3KWL1drF6sIcftOucmHHu5wZjHa402vCsN9nCRRgVKqqf14OwhGEs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
