travis:
  secure:
    BINSTAR_TOKEN: Mhnloc+M30epnocGj7KfZ7t5DjpPv2lPLeXWCePXp8ns0QloHP6Mx+4JMa4Kcpdn8v7AeCJZBusOxMWGYvYZXtaIVhWGtK8uyVz6Bybz4z+PhMydOj7mWrQjUZQFwPmQ1ba0CAiyW+Y2X2IL14EBhW+Hu3U8EgABKeyLtDaJmgiDCKg2KrUE+ueHnYe5lWqWzsInIUZZmMzo9yMJ9clIcgFQhqIPnunB/I5pzTt4vXyYbMQP0Q6qXld2U8WJHx7W3L+IJDOsj0Ht7CSCf6na9PtcwxJI+cPzxgTDr/ikp1FZLXogVfqLzUfSi1uCbimYevvFL85T7UweixuFig4RFEAxtsXxO3jyYjVnnl/h15605tmzMACdw+3fKvQpJFykxBDFFXQm2UsPPHvELaSw+j6AnQH5fOyCZ75fHMF6lD4WEp9RPhSq6JBWLM7KxMutqKHza/cWUg7sn3grgZleD9K2rvI9E0OFbIb9az+WFjfICiEy6TmA+q+fZM3yBKn5RqGF95z/bH8KkpgOK1MFGO7eXfpQOm/pKwBkqhZJBA6b0Q1WO03N7uqAFzN53moKZ67TmsOyYej3TtpNFMGU+I3VT90pdtEFpzWqZ/YkQbn4UD2yq+Q+KmecW7hype2FccJRVnUw1ELiP/cadeSqxcQkjzdb2rjvRypgntHg3IA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
